### ISSUE TITLE
Clarification on binding

### ISSUE THREAD

**Issue by dead-claudia** [domenic/proposal-import-function#10]
I saw in #6 that some non-literal strings are accepted. Is `import(someDynamicString)` okay, where `someDynamicString` is a string referencing a valid binding?

**Comment by dead-claudia** [comment]
Oh, and an unrelated comment: shouldn't this be listed in the [proposal repo](https://github.com/tc39/proposals) as a stage 0 proposal?

**Comment by domenic** [comment]
Yes, that is true. Is that unclear from the spec?

This has not been proposed to the committee and as such is not a stage 0 proposal.

Closing since it doesn't appear that there's a spec bug here, but happy to reopen if you can point out ways in which this is not clear.

**Comment by dead-claudia** [comment]
Okay. Thanks!
