### ISSUE TITLE
Expose import(id) to non-module scripts?

### ISSUE THREAD

**Issue by benjamn** [domenic/proposal-import-function#12]
If I understand correctly, prior to this proposal, an HTML `<script type=module>` tag like

``` html
<script type=module>
  import "./main.js";
</script>
```

was more or less equivalent to a non-module `<script>` tag that called `System.import`:

``` html
<script>
  System.import("./main.js");
</script>
```

What are the chances of using `import(id)` in this way, so that we can fully deprecate the global `System.import` API?

``` html
<script>
  import("./main.js");
</script>
```

Since `import` is a reserved keyword in scripts, there should be no problem with giving it a new meaning, a la `typeof` or `super`.

Presumably the parent module identifier used to resolve the imported identifier—that is, what exactly is `"./main.js"` relative to?—would either be `undefined` or something like the path of the calling script or HTML file.

**Comment by domenic** [comment]
This proposal already defines import() to work in scripts... all the details are in the spec + the HTML integration document.

**Comment by benjamn** [comment]
Ah yes, sorry for not reading more carefully!
