### ISSUE TITLE
Rename repo to proposal-import-function-like?

### ISSUE THREAD

**Issue by domenic** [domenic/proposal-import-function#14]
The name of this proposal is `import()`. But people need an alphanumeric name for URLs and babel plugins and such. I think "import-function" might be misleading since it's not a function. Perhaps "import-function-like" would be better? Suggestions welcome.

**Comment by domenic** [comment]
Maybe "import-call"

**Comment by matthewrobb** [comment]
import-invoke ?

**Comment by ljharb** [comment]
`import-parens`?

**Comment by klzns** [comment]
I think the thing that's most valuable of this import, is it dynamic or
async feature. So maybe:

dynamic-import or async-import

Em Sáb, 8 de out de 2016 22:08, Jordan Harband notifications@github.com
escreveu:

**Comment by Mouvedia** [comment]
Either `async-import` or `import-call`.

**Comment by matthewrobb** [comment]
Considering this is a syntax feature then perhaps name it import-expression

**Comment by domenic** [comment]
Thanks for the suggestions all! I liked most of them, and in the end "dynamic import" resonated with me the most.
