### ISSUE TITLE
Probably should syntactically disallow more than one argument?

### ISSUE THREAD

**Issue by domenic** [domenic/proposal-import-function#15]
Right now further arguments are ignored. But we could make it syntactically disallowed to pass more than one. That might be more future proof in case we eventually want to use them for something (although that seems unlikely).

**Comment by ljharb** [comment]
+1, since it's not actually a function, but a syntactic construct, it seems better to only allow one item (with perhaps only one optional trailing comma).

**Comment by domenic** [comment]
So, this is a bit tricky because of spread. E.g. should `import(...['a'])` work? Probably yes. Then I guess `import(...['a', 'b'])` or `import(...[])` has to be a runtime error, not a static error.

@allenwb @bterlson I could use some help figuring out the best way to spec this. Here are the ideas I've come up with so far:
- Change the grammar to not use ArgumentList, but instead a new production that only allows either `AssignmentExpression` or, I guess, `... AssignmentExpression`. I'd then have to modify ArgumentListEvaluation to work on this new production.
- Add some kind of "static semantics: early errors" restriction? I'm not sure exactly how to phrase it though.
- Give up on static errors entirely and just add a dynamic error after ArgumentListEvaluation if the list is not exactly of size 1.

In all of the above cases "dynamic error" in this case could be a rejected promise, or it could be a thrown error. I'd lean toward rejected promise I guess, since that's what we do for invalid arguments to async and promise-returning functions across the platform... but this is kind of like a syntax error, so maybe it should be thrown? The trickiness of this leads me to another option:
- Disallow spread entirely, so that all errors are static syntax errors.

**Comment by domenic** [comment]
I just realized runtime errors are annoying because we have to decide whether the result should be a rejected promise or a thrown error... I'll edit the above list of alternatives to reflect this new degree of freedom.

**Comment by ljharb** [comment]
I'm not sure why `import(...['a'])` should work when `import(...['a', 'b'])` doesn't. When would you want that?

**Comment by bmeck** [comment]
I vote to disallow spread and only accept 1 argument.

**Comment by domenic** [comment]
I guess that makes sense, and certainly does make things easier. With that in mind I think just using AssignmentExpression will be simplest instead of trying to restrict ArgumentList with early errors. Commit incoming. Thanks!

**Comment by matthewp** [comment]
Disallowing spread means this will be a SyntaxError, is that right?

**Comment by domenic** [comment]
Correct, in particular an early error since the script just won't parse.

**Comment by sashafirsov** [comment]
@domenic , is the runtime formation of arguments  a valid use case? If yes, the special treatment worth to be kept in same API convention as all others, i.e. over Promise error flow. The SyntaxError exception or resource not available from dynamic module management point of view are essentially same.

**Comment by sashafirsov** [comment]
-1 to rendering the error. It is OK to have an ASSERT but the convention of use could be extended by environment and it as long as functionality is not broken the warning is more than sufficient.

**Comment by wchargin** [comment]
> with perhaps only one optional trailing comma

As I interpret the spec, a trailing comma is disallowed.

Is this correct? Is this desired?

Babylon currently allows a trailing comma, while Flow’s parser does not.
See facebook/flow#7124.

**Comment by ljharb** [comment]
It seems reasonable to allow it.

**Comment by hax** [comment]
@ljharb If we add second param, shall we also support spread?

**Comment by ljharb** [comment]
It’s surely not my decision, but i wouldn’t expect spread to work on a static construct like this.

**Comment by wchargin** [comment]
@hax: Scroll up to see previous discussions about multiple arguments and
spread. The most recent comments are about allowing a syntactic trailing
comma _only_, not any additional arguments.
