### ISSUE TITLE
Tree shaking and partial imports.

### ISSUE THREAD

**Issue by DylanPiercey** [domenic/proposal-import-function#19]
Is this something that can be done here?

I figured something like

``` js
import('lodash', 'map').then(map => ...)
```

Just curious if this has been thought of.

**Comment by Mouvedia** [comment]
You meant `import(…` instead of `Import(…` right?

**Comment by DylanPiercey** [comment]
@Mouvedia was on a phone, but I fixed that.

**Comment by domenic** [comment]
I don't really understand this issue. What bug are your reporting with the current proposal? Are you trying to create another proposal? If so this isn't the place for it.

**Comment by DylanPiercey** [comment]
@domenic I am merely asking if there is something synonymous with

``` js
import { map } from 'lodash'
```

In this proposal.

**Comment by domenic** [comment]
You can do `import('lodash').then(ld => ld.map)`.

**Comment by DylanPiercey** [comment]
@domenic I am aware of that. Was just curious since obviously that doesn't support tree shaking.

**Comment by domenic** [comment]
From what I understand, tree-shaking is a nonstandard way of using modules supported by some ahead-of-time tooling that turns those modules into non-modules. It's not really something that informs the design of the language, but instead is something for those creating such tools to work through on their own.

**Comment by caridy** [comment]
@DylanPiercey to be precise here, if you have a tool that can do tree shaking on something like:

``` js
import * as foo from "foo";
foo.x('do something');
```

Assuming that foo exports a lot more than just `x`, then it is very likely that the same tool can work the same way with `import("foo")`.
