### ISSUE TITLE
What happens if the argument is not a string?

### ISSUE THREAD

**Issue by not-an-aardvark** [domenic/proposal-import-function#20]
It's possible I'm missing something in the spec, but it doesn't seem to be clear how `import()` handles cases like this:

``` js
const notAString = {};
import(notAString);
```

Based on the [runtime semantics](https://domenic.github.io/proposal-dynamic-import/#sec-import-call-runtime-semantics-evaluation), it looks like `HostPrepareImportedModule` would get called with the non-string value as _specifier_. But the summary of `HostPrepareImportedModule` appears to imply that _specifier_ must be a string.

Is _ImportCall_ supposed to convert the argument into a string (resulting in `[object Object]` getting imported)? Or would a runtime error get thrown in that case?

**Comment by ljharb** [comment]
It seems like between steps 4 and 5 of https://domenic.github.io/proposal-dynamic-import/#sec-import-call-runtime-semantics-evaluation, `specifier` should be ran through `? ToString()` to ensure it's a proper string.

**Comment by Mouvedia** [comment]
https://tc39.github.io/ecma262/#sec-tostring

**Comment by domenic** [comment]
Great catch, thank you!
