### ISSUE TITLE
Named vs default imports?

### ISSUE THREAD

**Issue by ljharb** [domenic/proposal-import-function#21]
Let's say I have a module that can be imported like so:
```js
import foo, { bar } from 'path';
```

How can I use `import()` to get both foo and bar? In the following code:
```js
import('path').then((x) => {
  // what is `x` here? `foo`? `bar`? an object?
});
```

**Comment by Ltrlg** [comment]
The promise is resolved with the module namespace (2.1.1, step 8.c.iv of
the current draft), i.e. `x` will be the same as in

import \* as x from 'path'

You can get the same behaviour as `foo` and `bar` with `x.default` and
`x.bar`, respectively.

Or by destructuring if you don’t require the live binding:

import('path').then(({default: foo, bar}) => {
  /\* … */
})

**Comment by matthewp** [comment]
It's the namespace object, so there's a `bar` and a `default`. It's equivalent of the imperative `import * as path from 'path'`.

edit: @Ltrlg literally beat me by a second! :)

**Comment by domenic** [comment]
Seems like this has been answered.

**Comment by ljharb** [comment]
Thanks for clarifying!

**Comment by knpwrs** [comment]
Any chance somebody can provide a link to "2.1.1, step 8.c.iv of the current draft"? I'm looking for a link to use for https://github.com/webpack/webpack.js.org/pull/1109.
