### ISSUE TITLE
Why separate out HostFetchImportedModule?

### ISSUE THREAD

**Issue by littledan** [domenic/proposal-import-function#3]
Could it instead be implicit in HostResolveImportedModule, and just say that that implicitly returns asynchronously?

**Comment by littledan** [comment]
Oops, posted this draft by accident. I meant to rewrite the report to say, explain why  (I think I understand).

**Comment by robpalme** [comment]
@littledan Please explain why the fetch and resolve are separate!

**Comment by domenic** [comment]
I mean, this seems like basic separation of responsibilities? You do two things, so you have two functions for them?

Also, HostFetchImportedModule is only needed for import(), not for top-level imports. So they kind of have to be separate.

**Comment by littledan** [comment]
To clarify further, using the example of the HTML embedding environment, HostResolveImportedModule can currently assume that scripts are already fetched because they were exposed to the embedder through [[RequestedModules]]; [HTML fetches these](https://html.spec.whatwg.org/#fetch-the-descendants-of-a-module-script) before it does anything that would end up calling HostResolveImportedModule.

I think it would be worth it to draw out the point that HostFetchImportedModule is sort of like dynamically adding an entry to [[RequestedModules]].

**Comment by robpalme** [comment]
That definitely helps fill in the gaps.  It kind of fully justifies HostFetchImportedModules existence:  a way to dynamically populate the existing cache mechanism.

**Comment by littledan** [comment]
It's not a cache; it's the only path to fetching the module.
