### ISSUE TITLE
Include hash and nonce as a second options parameter?

### ISSUE THREAD

**Issue by phistuck** [domenic/proposal-import-function#31]
See https://discourse.wicg.io/t/specifying-nonce-or-integrity-when-importing-modules/1861/5 for context.

**Comment by matthewp** [comment]
Is the plan to incorporate that into this proposal? I think that would be a mistake, as it would delay and possibly even kill the momentum that this proposal already has.

**Comment by domenic** [comment]
Yes, this would be a part of a future proposal that solves the issue for all imports. It is why we're reserving the second argument though!

**Comment by falsandtru** [comment]
Where is an open issue of this request? I want to validate integrity with dynamic import.
