### ISSUE TITLE
does babel support this feature?

### ISSUE THREAD

**Issue by zzzgit** [domenic/proposal-import-function#40]
does babel support this feature?
I found not
Is there a plugin for babel can achieve this?

**Comment by domenic** [comment]
I'm not sure. I'd suggest asking over on the Babel repository, not the spec repository, since I'm not associated with the Babel project.

**Comment by ljharb** [comment]
https://github.com/airbnb/babel-plugin-dynamic-import-node and https://github.com/airbnb/babel-plugin-dynamic-import-webpack are two.

**Comment by zzzgit** [comment]
thank very much

**Comment by GabrielDelepine** [comment]
I would prefer the plugin of the official babel repo https://github.com/babel/babel/tree/master/packages/babel-plugin-syntax-dynamic-import

**Comment by ljharb** [comment]
@GabrielDelepine that's the syntax plugin only, which both of the above transforms depend on - that is not sufficient to transpile it, solely to parse it.
