### ISSUE TITLE
Multiple imports

### ISSUE THREAD

**Issue by slanted** [domenic/proposal-import-function#54]
Forgive me if I missed something. But is there a provision for multiple imports / promises for this?

i.e. import(['module1', 'module2']).then(function(module1, module2) {

});

Been using something like this since jspm/systemjs and requirejs and I always see ugly Promise.all solutions which are some heinous  syntax that I hope doesn't make it into the proposal. A little sugar would be great.

**Comment by domenic** [comment]
No, Promise.all is the way to wait for multiple things in parallel in JavaScript and we have no intentions of moving away from that.
