### ISSUE TITLE
Is import() a function?

### ISSUE THREAD

**Issue by jhnns** [domenic/proposal-import-function#8]
Thanks for writing this up. I really love this spec because it feels very naturally to me to use an `import()` function when you want to import things on runtime and an `import` statement when you want to import things statically.

Although I really like the static nature of ES2015 modules, I also see the use-case for dynamic imports which enabled us to provide fallbacks in node when a module was not usable for whatever reason.

However, after reading the proposal I had some questions: 😁 

If I understood it correctly, `import()` would not be a regular function since you need information about the importing module (for instance when resolving relative specifiers). Is that correct? How will this extra-information be passed into the `HostResolveImportedModule`? Since `import()` _feels_ like a function, will I be able to do function-like things like:

``` javascript
const myImport = import;

typeof import === "function";
```

And how does this relate to `System.import()`? Is `System.import()` a regular function which means that module-relative specifiers would be impossible to implement?

**Comment by matthewp** [comment]
I'll let @domenic answer, but I'm pretty sure you are right, import() is not a function that you can assign to a variable.

We need a name for this type of construct (maybe there's already one?) of something that looks like a function but can't be assigned to a variable, can't .call/.apply it, etc.  `super()` is another example.

> And how does this relate to System.import()? Is System.import() a regular function which means that module-relative specifiers would be impossible to implement?

That's from a pretty old spec, it's been morphed a bit since then and its status is still up in the air. But yes, you are correct in that a global import function would not be able to resolve module-relative specifiers.

**Comment by forceuser** [comment]
is it be like `typeof`/`typeof()` ?

**Comment by domenic** [comment]
Yeah. It is a syntactic form like `super()`; it is not a function. Those code samples you give will be syntax errors.

> How will this extra-information be passed into the HostResolveImportedModule?

I think the spec is fairly clear on this; what can be clarified further?

> And how does this relate to System.import()? Is System.import() a regular function which means that module-relative specifiers would be impossible to implement?

`System.import()` or `System.loader.import()` is an idea from the loader collection of interesting ideas; as noted in this repo's README, it has issues, which you can kind of tell by following the links in the ideas collection to end up at https://whatwg.github.io/loader/#browser-loader-prototype-@@resolve which is just a giant TODO. One of the big issues is that it would indeed be impossible to spec module-relative specifiers, without relying on stack inspection ("dynamic scoping") to tell which source file a call appears in, which is not really compatible with the JavaScript model. A syntactic form does not have this problem.

**Comment by jhnns** [comment]
> I think the spec is fairly clear on this; what can be clarified further?

You're right, it's clear enough. It's just that I'm not familiar with the specification (and reading/understanding it). No worries 👍 

> One of the big issues is that it would indeed be impossible to spec module-relative specifiers, without relying on stack inspection ("dynamic scoping") to tell which source file a call appears in, which is not really compatible with the JavaScript model. A syntactic form does not have this problem.

That is a big problem indeed (and I didn't know that because I'm not following the discussions). Ideally dynamic imports should work exactly the same like their static counter-parts – with the exception that they return promises. I already had problems to imagine what the result of the promise would actually be, but that's probably inevitable and unfortunately something you just need to know.

Thanks for clarifying it 👍

**Comment by domenic** [comment]
\o/
